datasets:
  col0xdb1:
    reference_genotype: "col0"
    parent2_accessions:
      - "db1"
  # db1xcol0:
  #   reference_genotype: "db1"
  #   parent2_accessions:
  #     - "col0"
genome_fasta:
  col0: "../../annotations/Col-CC_Chr4.fasta"
  db1: "../../annotations/Db-1_Chr4.fasta"
genome_gff:
  col0: "../../annotations/Col-CC_Chr4.gff"
  db1: "../../annotations/Db-1_Chr4.gff"
organellar_fasta: "../../annotations/organeller.fasta"
organellar_gff: "../../annotations/organeller.gff"
barcode_whitelist: "../annotations/3M-february-2018.txt"
